sudo: required
services:
 - docker

before_install:
 - docker build -t muzammilmomin/docker-react -f Dockerfile.dev .

script:
 - docker run -p 80:80 -d muzammilmomin/docker-react 
 
deploy:
 provider: elasticbeanstalk
 region: "ap-south-1"
 app: "docker-react"
 env: "DockerReact-env"
 bucket_name: "elasticbeanstalk-ap-south-1-653654105746"
 bucket_path: "docker-react"
 on:
  branch: master
 access_key_id: "$aws_access_key"
 secret_access_key:
  secure: "$aws_secret_key"

